-- =============================================================
-- Backfill: restore the state and central schemes that were only
-- ever in the bundled catalogue (src/data/schemes.ts)
--
-- Wiring a real Supabase project into this session today (to fix login)
-- surfaced something worth knowing: `useSchemes()` prefers this live
-- `schemes` table over the bundled fallback whenever it has rows, and this
-- table held exactly ten central schemes and zero state ones. So the
-- Schemes page had been showing FEWER schemes with the real database
-- connected than the bundled fallback alone provided — every state scheme
-- (Bhavantar Bhugtan, Namo Shetkari, KALIA, Rythu Bharosa, Krishak Bandhu,
-- and thirteen more) and sixteen more central schemes had gone invisible.
--
-- This migration is that catalogue's other 32 rows — everything in
-- src/data/schemes.ts not already live and not already covered by
-- 20260908000000_state_farmer_schemes.sql. Generated directly from that
-- file (via esbuild + a small Node script) rather than retyped by hand, so
-- every field matches the bundled data exactly.
--
-- Two ids were deliberately left out, both already present with equivalent
-- content under a different primary key:
--   - 'enam' (bundled) is the same scheme as the live 'e-nam' row. Inserting
--     it would not conflict — different id — and would just duplicate
--     e-NAM under two rows. Left out rather than silently duplicated.
--   - The nine other live ids (kcc, pkvy, pm-kisan, pm-kmy, pm-kusum,
--     pmfby, pmksy, smam, soil-health-card) already match the bundled id
--     exactly, so ON CONFLICT DO NOTHING below already handles them
--     correctly without needing to be excluded by hand.
--
-- ON CONFLICT DO NOTHING: re-running this must not clobber a row an admin
-- has since corrected through the app.
-- =============================================================

INSERT INTO public.schemes
  (id, name, name_hi, description, description_hi, eligibility, eligibility_hi, benefits, benefits_hi, link, category, state, is_active)
VALUES
  ('pm-dhan-dhaanya', 'PM Dhan-Dhaanya Krishi Yojana', 'पीएम धन-धान्य कृषि योजना', 'Flagship district-level programme converging 36 existing schemes to raise productivity in low-yield districts', 'कम उपज वाले जिलों में उत्पादकता बढ़ाने हेतु 36 मौजूदा योजनाओं को जोड़ने वाला प्रमुख जिला-स्तरीय कार्यक्रम', 'Farmers in the 100 identified low-productivity districts', 'चिन्हित 100 कम उत्पादकता वाले जिलों के किसान', '₹24,000 crore annually for six years; aims to benefit 1.7 crore farmers', 'छह वर्षों तक सालाना ₹24,000 करोड़; 1.7 करोड़ किसानों को लाभ का लक्ष्य', 'https://www.india.gov.in/', 'income', NULL, true),
  ('natural-farming', 'National Mission on Natural Farming (NMNF)', 'राष्ट्रीय प्राकृतिक खेती मिशन', 'Promotes chemical-free farming using on-farm biomass and traditional practices', 'खेत की जैव सामग्री और पारंपरिक तरीकों से रसायन-मुक्त खेती को बढ़ावा', 'Farmers willing to adopt natural farming, typically in clusters', 'प्राकृतिक खेती अपनाने के इच्छुक किसान, सामान्यतः समूहों में', 'Input assistance, training, and support for bio-input resource centres', 'आदान सहायता, प्रशिक्षण, और जैव-आदान संसाधन केंद्रों हेतु सहायता', 'https://naturalfarming.dac.gov.in/', 'organic', NULL, true),
  ('aif', 'Agriculture Infrastructure Fund (AIF)', 'कृषि अवसंरचना कोष (एआईएफ)', 'Long-term financing for post-harvest infrastructure and community farming assets', 'कटाई-उपरांत अवसंरचना और सामुदायिक कृषि परिसंपत्तियों हेतु दीर्घकालिक वित्तपोषण', 'Farmers, FPOs, PACS, SHGs, agri-entrepreneurs and startups', 'किसान, एफपीओ, पैक्स, स्वयं सहायता समूह, कृषि उद्यमी और स्टार्टअप', '3% interest subvention and credit guarantee on eligible loans', 'पात्र ऋणों पर 3% ब्याज छूट और ऋण गारंटी', 'https://agriinfra.dac.gov.in/', 'infrastructure', NULL, true),
  ('fpo-scheme', 'Formation and Promotion of 10,000 FPOs', '10,000 एफपीओ का गठन और संवर्धन', 'Builds farmer producer organisations so smallholders gain collective bargaining power', 'किसान उत्पादक संगठन बनाती है ताकि छोटे किसानों को सामूहिक सौदेबाजी शक्ति मिले', 'Groups of farmers forming or joining an FPO', 'एफपीओ बनाने या जुड़ने वाले किसानों के समूह', 'Financial assistance per FPO, plus equity grant and credit guarantee support', 'प्रति एफपीओ वित्तीय सहायता, साथ ही इक्विटी अनुदान और ऋण गारंटी सहायता', 'https://sfacindia.com/', 'market', NULL, true),
  ('midh', 'Mission for Integrated Development of Horticulture (MIDH)', 'एकीकृत बागवानी विकास मिशन (एमआईडीएच)', 'Supports fruit, vegetable, spice and flower cultivation end to end', 'फल, सब्जी, मसाला और फूल की खेती को शुरू से अंत तक सहायता', 'Horticulture farmers, nurseries, FPOs and cooperatives', 'बागवानी किसान, नर्सरी, एफपीओ और सहकारी समितियां', 'Assistance for planting material, protected cultivation, cold chain and post-harvest units', 'रोपण सामग्री, संरक्षित खेती, शीत श्रृंखला और कटाई-उपरांत इकाइयों हेतु सहायता', 'https://midh.gov.in/', 'inputs', NULL, true),
  ('nfsm', 'National Food Security Mission (NFSM)', 'राष्ट्रीय खाद्य सुरक्षा मिशन (एनएफएसएम)', 'Raises production of rice, wheat, pulses, coarse cereals and nutri-cereals', 'चावल, गेहूं, दलहन, मोटे अनाज और पोषक अनाज का उत्पादन बढ़ाती है', 'Farmers in identified districts growing target crops', 'लक्षित फसल उगाने वाले चिन्हित जिलों के किसान', 'Subsidised certified seed, inputs, machinery and demonstration support', 'सब्सिडी वाले प्रमाणित बीज, आदान, मशीनरी और प्रदर्शन सहायता', 'https://www.nfsm.gov.in/', 'inputs', NULL, true),
  ('pulses-mission', 'Mission for Aatmanirbharta in Pulses', 'दलहन में आत्मनिर्भरता मिशन', 'Six-year mission to make India self-reliant in pulses, focusing on tur, urad and masoor', 'तुअर, उड़द और मसूर पर केंद्रित, भारत को दलहन में आत्मनिर्भर बनाने का छह-वर्षीय मिशन', 'Pulse-growing farmers, with assured procurement arrangements', 'दलहन उगाने वाले किसान, सुनिश्चित खरीद व्यवस्था के साथ', 'Quality seed access, productivity support and assured procurement', 'गुणवत्ता बीज उपलब्धता, उत्पादकता सहायता और सुनिश्चित खरीद', 'https://www.nfsm.gov.in/', 'inputs', NULL, true),
  ('nmeo-op', 'National Mission on Edible Oils – Oil Palm (NMEO-OP)', 'खाद्य तेल राष्ट्रीय मिशन – ऑयल पाम', 'Expands domestic oilseed and oil palm cultivation to cut import dependence', 'आयात निर्भरता घटाने हेतु घरेलू तिलहन और ऑयल पाम की खेती का विस्तार', 'Farmers in identified oil palm and oilseed zones', 'चिन्हित ऑयल पाम और तिलहन क्षेत्रों के किसान', 'Planting material assistance, viability price support and input subsidy', 'रोपण सामग्री सहायता, व्यवहार्यता मूल्य समर्थन और आदान सब्सिडी', 'https://nmeo.dac.gov.in/', 'inputs', NULL, true),
  ('rkvy', 'Rashtriya Krishi Vikas Yojana (RKVY)', 'राष्ट्रीय कृषि विकास योजना (आरकेवीवाई)', 'Flexible state-led funding for agriculture and allied sector projects', 'कृषि और संबद्ध क्षेत्र परियोजनाओं हेतु लचीला राज्य-नेतृत्व वाला वित्तपोषण', 'Routed through state agriculture departments; farmers benefit via state projects', 'राज्य कृषि विभागों के माध्यम से; किसान राज्य परियोजनाओं से लाभान्वित', 'Funds infrastructure, innovation, agri-startups and state-priority interventions', 'अवसंरचना, नवाचार, कृषि स्टार्टअप और राज्य-प्राथमिकता हस्तक्षेपों का वित्तपोषण', 'https://rkvy.da.gov.in/', 'infrastructure', NULL, true),
  ('enwr', 'Electronic Negotiable Warehouse Receipt (e-NWR)', 'इलेक्ट्रॉनिक परक्राम्य गोदाम रसीद (ई-एनडब्ल्यूआर)', 'Store produce in a registered warehouse and borrow against the receipt instead of distress-selling', 'पंजीकृत गोदाम में उपज रखें और मजबूरी में बेचने के बजाय रसीद पर ऋण लें', 'Farmers storing produce in WDRA-registered warehouses', 'डब्ल्यूडीआरए-पंजीकृत गोदामों में उपज रखने वाले किसान', 'Pledge finance against stored stock, letting you sell when prices recover', 'रखे स्टॉक पर गिरवी वित्त, जिससे दाम सुधरने पर बेच सकें', 'https://wdra.gov.in/', 'market', NULL, true),
  ('pmmsy', 'Pradhan Mantri Matsya Sampada Yojana (PMMSY)', 'प्रधानमंत्री मत्स्य संपदा योजना (पीएमएमएसवाई)', 'Develops fisheries infrastructure, aquaculture and fisher livelihoods', 'मत्स्य अवसंरचना, जलकृषि और मछुआरों की आजीविका का विकास', 'Fishers, fish farmers, fish worker cooperatives and entrepreneurs', 'मछुआरे, मत्स्य किसान, मत्स्य श्रमिक सहकारी समितियां और उद्यमी', 'Subsidy on ponds, hatcheries, cold chain and fishing equipment', 'तालाब, हैचरी, शीत श्रृंखला और मत्स्य उपकरण पर सब्सिडी', 'https://pmmsy.dof.gov.in/', 'allied', NULL, true),
  ('ahidf', 'Animal Husbandry Infrastructure Development Fund (AHIDF)', 'पशुपालन अवसंरचना विकास कोष (एएचआईडीएफ)', 'Credit-linked support for dairy, meat processing and animal feed plants', 'डेयरी, मांस प्रसंस्करण और पशु आहार संयंत्रों हेतु ऋण-आधारित सहायता', 'Individual entrepreneurs, FPOs, MSMEs, Section 8 companies and private firms', 'व्यक्तिगत उद्यमी, एफपीओ, एमएसएमई, धारा 8 कंपनियां और निजी फर्में', '3% interest subvention with credit guarantee for eligible projects', 'पात्र परियोजनाओं हेतु ऋण गारंटी के साथ 3% ब्याज छूट', 'https://ahidf.udyamimitra.in/', 'allied', NULL, true),
  ('gokul-mission', 'Rashtriya Gokul Mission', 'राष्ट्रीय गोकुल मिशन', 'Conserves and improves indigenous cattle breeds and raises milk productivity', 'देशी गोवंश नस्लों का संरक्षण और सुधार तथा दुग्ध उत्पादकता में वृद्धि', 'Dairy farmers and cattle rearers', 'डेयरी किसान और पशुपालक', 'Access to quality breeding services, artificial insemination and gokul grams', 'गुणवत्ता प्रजनन सेवाएं, कृत्रिम गर्भाधान और गोकुल ग्राम तक पहुंच', 'https://dahd.nic.in/', 'allied', NULL, true),
  ('beekeeping', 'National Beekeeping & Honey Mission (NBHM)', 'राष्ट्रीय मधुमक्खी पालन एवं शहद मिशन', 'Promotes scientific beekeeping as an additional income stream alongside cropping', 'खेती के साथ अतिरिक्त आय स्रोत के रूप में वैज्ञानिक मधुमक्खी पालन को बढ़ावा', 'Farmers, beekeepers, SHGs and FPOs', 'किसान, मधुमक्खी पालक, स्वयं सहायता समूह और एफपीओ', 'Support for bee boxes, honey processing units and testing labs', 'मधुमक्खी बक्से, शहद प्रसंस्करण इकाइयों और परीक्षण प्रयोगशालाओं हेतु सहायता', 'https://nbb.gov.in/', 'allied', NULL, true),
  ('agmarknet', 'AGMARKNET', 'एगमार्कनेट', 'Official daily price and arrival data from more than 3,000 mandis nationwide', 'देशभर की 3,000 से अधिक मंडियों से आधिकारिक दैनिक मूल्य और आवक आंकड़े', 'Open to everyone — no registration needed', 'सभी के लिए खुला — पंजीकरण की आवश्यकता नहीं', 'Check today''s rate before you sell, so you can negotiate from a known price', 'बेचने से पहले आज का भाव देखें, ताकि आप ज्ञात मूल्य पर मोलभाव कर सकें', 'https://agmarknet.gov.in/', 'market', NULL, true),
  ('kisan-call-centre', 'Kisan Call Centre (1800-180-1551)', 'किसान कॉल सेंटर (1800-180-1551)', 'Toll-free agricultural advisory from experts in your own language', 'विशेषज्ञों से आपकी अपनी भाषा में निःशुल्क कृषि सलाह', 'Any farmer, any time — no registration', 'कोई भी किसान, कभी भी — पंजीकरण नहीं', 'Free expert answers on crops, pests, weather and schemes', 'फसल, कीट, मौसम और योजनाओं पर निःशुल्क विशेषज्ञ उत्तर', 'https://mkisan.gov.in/', 'inputs', NULL, true),
  ('mp-kisan-kalyan', 'Mukhyamantri Kisan Kalyan Yojana', 'मुख्यमंत्री किसान कल्याण योजना', 'State income support paid on top of PM-KISAN to MP farmers', 'मध्य प्रदेश के किसानों को पीएम-किसान के अतिरिक्त राज्य आय सहायता', 'MP farmers already registered under PM-KISAN', 'पीएम-किसान में पहले से पंजीकृत मध्य प्रदेश के किसान', 'Additional annual support credited directly to the bank account', 'अतिरिक्त वार्षिक सहायता सीधे बैंक खाते में', 'https://saara.mp.gov.in/', 'income', 'Madhya Pradesh', true),
  ('mp-bhavantar', 'Bhavantar Bhugtan Yojana', 'भावांतर भुगतान योजना', 'Pays the gap when the market price falls below the notified support price', 'बाजार भाव अधिसूचित समर्थन मूल्य से नीचे जाने पर अंतर की राशि देती है', 'Registered MP farmers selling notified crops in mandis', 'मंडियों में अधिसूचित फसल बेचने वाले पंजीकृत मध्य प्रदेश के किसान', 'Price-difference compensation credited after mandi sale', 'मंडी में बिक्री के बाद मूल्य-अंतर मुआवजा', 'https://mpeuparjan.nic.in/', 'market', 'Madhya Pradesh', true),
  ('mh-namo-shetkari', 'Namo Shetkari Mahasanman Nidhi', 'नमो शेतकरी महासन्मान निधि', 'Maharashtra state top-up to PM-KISAN income support', 'पीएम-किसान आय सहायता पर महाराष्ट्र राज्य की अतिरिक्त राशि', 'Maharashtra farmers eligible under PM-KISAN', 'पीएम-किसान के पात्र महाराष्ट्र के किसान', 'Extra annual installments alongside the central transfer', 'केंद्रीय हस्तांतरण के साथ अतिरिक्त वार्षिक किस्तें', 'https://krishi.maharashtra.gov.in/', 'income', 'Maharashtra', true),
  ('od-kalia', 'KALIA Yojana', 'कालिया योजना', 'Livelihood and cultivation support for small farmers, sharecroppers and landless labourers', 'छोटे किसानों, बटाईदारों और भूमिहीन मजदूरों हेतु आजीविका और खेती सहायता', 'Small and marginal farmers, cultivators and landless agricultural households in Odisha', 'ओडिशा के छोटे और सीमांत किसान, कृषक और भूमिहीन कृषि परिवार', 'Cultivation assistance, livelihood support and life insurance cover', 'खेती सहायता, आजीविका समर्थन और जीवन बीमा कवर', 'https://kalia.odisha.gov.in/', 'income', 'Odisha', true),
  ('tg-rythu-bharosa', 'Rythu Bharosa', 'रायथु भरोसा', 'Per-acre investment support paid ahead of each cropping season', 'प्रत्येक फसल मौसम से पहले दी जाने वाली प्रति एकड़ निवेश सहायता', 'Landholding farmers in Telangana', 'तेलंगाना के भूमिधारक किसान', 'Season-wise per-acre payment to fund seed and fertiliser before sowing', 'बुवाई से पहले बीज और उर्वरक हेतु मौसमवार प्रति एकड़ भुगतान', 'https://rythubharosa.telangana.gov.in/', 'income', 'Telangana', true),
  ('ap-annadata', 'Annadata Sukhibhava', 'अन्नदाता सुखीभव', 'State investment support for farmer families, combined with the central PM-KISAN transfer', 'केंद्रीय पीएम-किसान हस्तांतरण के साथ किसान परिवारों हेतु राज्य निवेश सहायता', 'Eligible farmer families in Andhra Pradesh including tenant farmers', 'किरायेदार किसानों सहित आंध्र प्रदेश के पात्र किसान परिवार', 'Annual financial assistance credited directly to the bank account', 'वार्षिक वित्तीय सहायता सीधे बैंक खाते में', 'https://apagrisnet.gov.in/', 'income', 'Andhra Pradesh', true),
  ('wb-krishak-bandhu', 'Krishak Bandhu', 'कृषक बंधु', 'Assured annual assistance plus death benefit cover for farming families', 'किसान परिवारों हेतु सुनिश्चित वार्षिक सहायता और मृत्यु लाभ कवर', 'Farmers and recorded bargadars in West Bengal', 'पश्चिम बंगाल के किसान और दर्ज बरगादार', 'Per-acre annual support in two installments, plus one-time death benefit', 'दो किस्तों में प्रति एकड़ वार्षिक सहायता, साथ ही एकमुश्त मृत्यु लाभ', 'https://krishakbandhu.wb.gov.in/', 'income', 'West Bengal', true),
  ('hr-meri-fasal', 'Meri Fasal Mera Byora', 'मेरी फसल मेरा ब्योरा', 'Single registration portal linking crop details to procurement, compensation and subsidies', 'फसल विवरण को खरीद, मुआवजे और सब्सिडी से जोड़ने वाला एकल पंजीकरण पोर्टल', 'All Haryana farmers', 'हरियाणा के सभी किसान', 'One registration unlocks MSP procurement, damage compensation and scheme benefits', 'एक पंजीकरण से एमएसपी खरीद, क्षति मुआवजा और योजना लाभ मिलते हैं', 'https://fasal.haryana.gov.in/', 'market', 'Haryana', true),
  ('rj-kisan-mitra-urja', 'Mukhyamantri Kisan Mitra Urja Yojana', 'मुख्यमंत्री किसान मित्र ऊर्जा योजना', 'Electricity bill subsidy for agricultural pump connections', 'कृषि पंप कनेक्शनों हेतु बिजली बिल सब्सिडी', 'Rajasthan farmers with metered agricultural connections', 'मीटर वाले कृषि कनेक्शन वाले राजस्थान के किसान', 'Monthly subsidy against the electricity bill, up to a notified cap', 'अधिसूचित सीमा तक बिजली बिल पर मासिक सब्सिडी', 'https://energy.rajasthan.gov.in/', 'machinery', 'Rajasthan', true),
  ('jh-krishi-ashirwad', 'Mukhyamantri Krishi Ashirwad Yojana', 'मुख्यमंत्री कृषि आशीर्वाद योजना', 'Per-acre grant to help small farmers meet sowing-season costs', 'छोटे किसानों को बुवाई मौसम की लागत पूरी करने हेतु प्रति एकड़ अनुदान', 'Small and marginal farmers in Jharkhand', 'झारखंड के छोटे और सीमांत किसान', 'Direct per-acre transfer before the Kharif season', 'खरीफ मौसम से पहले सीधा प्रति एकड़ हस्तांतरण', 'https://jrfry.jharkhand.gov.in/', 'income', 'Jharkhand', true),
  ('ka-raitha-siri', 'Raitha Siri', 'रायथा सिरी', 'Incentive for cultivating millets and other nutri-cereals', 'बाजरा और अन्य पोषक अनाज की खेती हेतु प्रोत्साहन', 'Karnataka farmers growing notified millet crops', 'अधिसूचित बाजरा फसल उगाने वाले कर्नाटक के किसान', 'Per-hectare incentive credited directly, encouraging crop diversification', 'सीधे जमा प्रति हेक्टेयर प्रोत्साहन, जो फसल विविधीकरण को बढ़ावा देता है', 'https://raitamitra.karnataka.gov.in/', 'inputs', 'Karnataka', true),
  ('gj-kisan-suryodaya', 'Kisan Suryodaya Yojana', 'किसान सूर्योदय योजना', 'Daytime electricity supply for irrigation instead of night-time pumping', 'रात में पंप चलाने के बजाय सिंचाई हेतु दिन में बिजली आपूर्ति', 'Gujarat farmers with agricultural power connections', 'कृषि बिजली कनेक्शन वाले गुजरात के किसान', 'Reliable daytime power, removing the need to irrigate at night', 'भरोसेमंद दिन की बिजली, जिससे रात में सिंचाई की जरूरत खत्म', 'https://gujaratindia.gov.in/', 'irrigation', 'Gujarat', true),
  ('br-diesel-anudan', 'Diesel Anudan Yojana', 'डीजल अनुदान योजना', 'Diesel subsidy for irrigating standing crops during deficient rainfall', 'कम वर्षा के दौरान खड़ी फसल की सिंचाई हेतु डीजल सब्सिडी', 'Bihar farmers irrigating with diesel pump sets during drought conditions', 'सूखे में डीजल पंप सेट से सिंचाई करने वाले बिहार के किसान', 'Per-acre diesel cost reimbursement for each irrigation round', 'प्रत्येक सिंचाई चक्र हेतु प्रति एकड़ डीजल लागत की प्रतिपूर्ति', 'https://dbtagriculture.bihar.gov.in/', 'irrigation', 'Bihar', true),
  ('up-kisan-uday', 'UP Agriculture Department Schemes (Kisan Registration)', 'उत्तर प्रदेश कृषि विभाग योजनाएं (किसान पंजीकरण)', 'Single UP portal for subsidy on seed, machinery, solar pumps and input assistance', 'बीज, मशीनरी, सौर पंप और आदान सहायता पर सब्सिडी हेतु एकल उत्तर प्रदेश पोर्टल', 'Registered farmers in Uttar Pradesh', 'उत्तर प्रदेश के पंजीकृत किसान', 'Access to state subsidies through one registration and token system', 'एक पंजीकरण और टोकन प्रणाली से राज्य सब्सिडी तक पहुंच', 'https://upagriculture.com/', 'inputs', 'Uttar Pradesh', true),
  ('pb-crop-diversification', 'Crop Diversification & Paddy Straw Management', 'फसल विविधीकरण एवं पराली प्रबंधन', 'Incentives to shift away from paddy and to manage stubble without burning', 'धान से हटने और बिना जलाए पराली प्रबंधन हेतु प्रोत्साहन', 'Punjab farmers adopting alternate crops or in-situ straw management', 'वैकल्पिक फसल या इन-सीटू पराली प्रबंधन अपनाने वाले पंजाब के किसान', 'Machinery subsidy for Happy Seeder and balers, plus diversification incentive', 'हैप्पी सीडर और बेलर पर मशीनरी सब्सिडी, साथ ही विविधीकरण प्रोत्साहन', 'https://agri.punjab.gov.in/', 'machinery', 'Punjab', true),
  ('tn-uzhavan', 'Uzhavan App & TN Agriculture Schemes', 'उझवन ऐप और तमिलनाडु कृषि योजनाएं', 'Single access point for subsidies, crop insurance, mandi prices and machinery booking', 'सब्सिडी, फसल बीमा, मंडी भाव और मशीनरी बुकिंग हेतु एकल पहुंच बिंदु', 'Tamil Nadu farmers', 'तमिलनाडु के किसान', 'Book farm machinery, check subsidies and apply for schemes from one place', 'एक ही जगह से कृषि मशीनरी बुक करें, सब्सिडी देखें और योजनाओं हेतु आवेदन करें', 'https://www.tnagrisnet.tn.gov.in/', 'machinery', 'Tamil Nadu', true)
ON CONFLICT (id) DO NOTHING;
